---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files
    - repo: https://github.com/thlorenz/doctoc
      rev: v2.2.0
      hooks:
          - id: doctoc
    - repo: https://github.com/prettier/pre-commit
      rev: 57f39166b5a5a504d6808b87ab98d41ebf095b46
      hooks:
          - id: prettier
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.1
      hooks:
          - id: yamlfmt
    - repo: https://github.com/charliermarsh/ruff-pre-commit
      rev: v0.11.3
      hooks:
          - id: ruff
            args: [--fix]
